spring:
  application:
    name: nothing-demo
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC
    hikari.driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8001
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

log:
  dir: D:\temp\log
management:
  endpoint:
    health:
      show-details: always
#  http://localhost:8000/actuator/health 检测服务
#  http://localhost:8000/actuator   可用检测点连接

