spring:
  application:
    name: nothing-demo
  redis:
    database: 1
    host: localhost
    port: 6379
#    password: SIJ*sh9832
#    host: r-2zebd8k5j3p83xbw6w.redis.rds.aliyuncs.com
  datasource:
    username: root
    password: mysql123
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    hikari.driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8001
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml

#log:
#  dir: D:\temp\log
management:
  endpoint:
    health:
      show-details: always
#  http://localhost:8000/actuator/health 检测服务
#  http://localhost:8000/actuator   可用检测点连接
redis-stream:
  names: test1,test2
  groups: grouptest1

canal:
  destination: hexin
  server: localhost:1111

